name: Replace-With-Your-Action-Name
description: Replace-With-Your-Action-Description
runs:
  using: composite
  steps:

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: build Docker
      run: docker build . --file src\main\docker\Dockerfile.jvm --tag academy:v1
      shell: bash
